version: '2'

services:
  postgres9:
    image: postgres:9.4
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - '/var/run/postgres.sock:/var/run/postgres/postgres.sock'
      - data:/var/lib/postgresql/data

volumes:
  data: {}
