version: '2'

services:
  postgres9:
    image: postgres:9.4
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}