version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        environment:
            DATABASE_URL: postgresql://ubuntu:ubuntu@<host>:5432/ubuntu
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"