name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_HOST: 127.0.0.1
  DATABASE_PORT: 5432
  POSTGRES_DB: postgres
  DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/postgres

jobs:

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '12', '14', '16' ]
        os: [ubuntu-latest]

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - name: ♻️ Check out Git Repository
      uses: actions/checkout@v2

    - name: 🐘 Configure Postgres
      uses: ./Docker/
      with:
        postgresql password: example
        postgresql init scripts: ../config

    - name: 🔖  Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: ⬇️  Install npm dependencies
      run: npm install

    - name: 🔥 Test database connection
      run: npm run test:db:connection

    - name: ✅  Run tests
      run: npm run test
